services:
  - type: web
    name: ctfd
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 "CTFd:create_app()"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ctfd-db
          property: connectionString
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/CTFd/uploads
      - key: SECRET_KEY
        generateValue: true
databases:
  - name: ctfd-db
    plan: free
